name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies and build 🔧
        run: pnpm install --frozen-lockfile && pnpm build
      - name: Publish package on NPM 📦
        run: pnpm publish --new-version $(echo "${{ github.event.release.tag_name }}" | sed "s/v//") --no-commit-hooks --no-git-tag-version
