name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies and build 🔧
        run: pnpm install && pnpm build
      - name: Set version
        run: npm version $(echo "${{ github.event.release.tag_name }}" | sed "s/v//") --no-git-tag-version
      - name: Publish package on NPM 📦
        run: npm publish --provenance --access public
